packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  zod: ^4.1.13
  "next": ^15.3.4
  "@tanstack/react-query": ^5.75.5

  # sentry
  "@sentry/nextjs": ^9.34.0

  # tools
  typescript: ^5.9.3
  tailwindcss: ^3.4.17
  postcss: ^8.5.1
  autoprefixer: ^10.4.20
  tsup: ^8.3.6 # @deperecated
  tsdown: ^0.16.7

  #convex
  convex: ^1.30.0
  # NOTE: @convex-dev/better-auth@0.9.7은 better-auth@1.3.43을 요구함
  # 1.4.x에서는 passkey 플러그인이 @better-auth/passkey로 분리되어 호환되지 않음
  better-auth: 1.3.34
  "@convex-dev/better-auth": ^0.9.9
  "@better-auth/expo": 1.3.34

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5
  orpc:
    "@orpc/client": "^1.2.0"
    "@orpc/openapi": "^1.2.0"
    "@orpc/react": "^1.2.0"
    "@orpc/react-query": "^1.2.0"
    "@orpc/server": "^1.2.0"
    "@orpc/zod": "^1.2.0"
  payload:
    "@payloadcms/db-postgres": "^3.44.0"
    "@payloadcms/live-preview-react": "^3.44.0"
    "@payloadcms/next": "^3.44.0"
    "@payloadcms/plugin-sentry": "^3.44.0"
    "@payloadcms/richtext-lexical": "^3.44.0"
    "@payloadcms/ui": "^3.44.0"
    "payload": "^3.44.0"
  prisma6:
    "@prisma/client": ^6.10.1
    "@prisma/adapter-d1": ^6.10.1
    prisma: ^6.10.1
  auth:
    better-auth: ^1.2.12
    "@better-auth/cli": ^1.2.12

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - prisma
