/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationIndexRouteImport } from './routes/application/index'
import { Route as SCodeRouteImport } from './routes/s/$code'
import { Route as OnboardingStepRouteImport } from './routes/onboarding/$step'
import { Route as ApplicationIdRouteImport } from './routes/application/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationIndexRoute = ApplicationIndexRouteImport.update({
  id: '/application/',
  path: '/application/',
  getParentRoute: () => rootRouteImport,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const ApplicationIdRoute = ApplicationIdRouteImport.update({
  id: '/application/$id',
  path: '/application/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/application/$id': typeof ApplicationIdRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/s/$code': typeof SCodeRoute
  '/application': typeof ApplicationIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/application/$id': typeof ApplicationIdRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/s/$code': typeof SCodeRoute
  '/application': typeof ApplicationIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/application/$id': typeof ApplicationIdRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/s/$code': typeof SCodeRoute
  '/application/': typeof ApplicationIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/application/$id'
    | '/onboarding/$step'
    | '/s/$code'
    | '/application'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/application/$id'
    | '/onboarding/$step'
    | '/s/$code'
    | '/application'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/application/$id'
    | '/onboarding/$step'
    | '/s/$code'
    | '/application/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  ApplicationIdRoute: typeof ApplicationIdRoute
  SCodeRoute: typeof SCodeRoute
  ApplicationIndexRoute: typeof ApplicationIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application/': {
      id: '/application/'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof ApplicationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/application/$id': {
      id: '/application/$id'
      path: '/application/$id'
      fullPath: '/application/$id'
      preLoaderRoute: typeof ApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OnboardingRouteRouteChildren {
  OnboardingStepRoute: typeof OnboardingStepRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingStepRoute: OnboardingStepRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  ApplicationIdRoute: ApplicationIdRoute,
  SCodeRoute: SCodeRoute,
  ApplicationIndexRoute: ApplicationIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
