import type { LucideProps } from "lucide-react";
import {
	ArrowLeft,
	ArrowRight,
	ArrowUpDown,
	BookOpen,
	Check,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Church,
	Copy,
	CopyCheck,
	CornerDownLeft,
	CornerDownRight,
	Github,
	Home,
	Info,
	Instagram,
	Loader2,
	Menu,
	Moon,
	MoreHorizontal,
	MoveLeft,
	MoveRight,
	Notebook,
	NotebookPen,
	PanelRight,
	PartyPopper,
	Search,
	SlidersHorizontal,
	Sun,
	UserPlus,
	Users,
	X,
	Youtube,
} from "lucide-react";
import React from "react";

export const Icons = {
	ArrowUpDown: (props: LucideProps) => <ArrowUpDown {...props} />,
	MoreHorizontal: (props: LucideProps) => <MoreHorizontal {...props} />,
	ChevronLeft: (props: LucideProps) => <ChevronLeft {...props} />,
	ChevronRight: (props: LucideProps) => <ChevronRight {...props} />,
	Menu: (props: LucideProps) => <Menu {...props} />,
	X: (props: LucideProps) => <X {...props} />,
	Sun: (props: LucideProps) => <Sun {...props} />,
	Moon: (props: LucideProps) => <Moon {...props} />,
	ChevronDown: (props: LucideProps) => <ChevronDown {...props} />,
	ChevronUp: (props: LucideProps) => <ChevronUp {...props} />,
	Users: (props: LucideProps) => <Users {...props} />,
	UserPlus: (props: LucideProps) => <UserPlus {...props} />,
	Church: (props: LucideProps) => <Church {...props} />,
	Github: (props: LucideProps) => <Github {...props} />,
	Instagram: (props: LucideProps) => <Instagram {...props} />,
	Youtube: (props: LucideProps) => <Youtube {...props} />,
	Search: (props: LucideProps) => <Search {...props} />,
	Notebook: (props: LucideProps) => <Notebook {...props} />,
	NotebookPen: (props: LucideProps) => <NotebookPen {...props} />,
	Home: (props: LucideProps) => <Home {...props} />,
	PanelRight: (props: LucideProps) => <PanelRight {...props} />,
	Check: (props: LucideProps) => <Check {...props} />,
	Loader2: (props: LucideProps) => <Loader2 {...props} />,
	SlidersHorizontal: (props: LucideProps) => <SlidersHorizontal {...props} />,
	BookOpen: (props: LucideProps) => <BookOpen {...props} />,
	MoveLeft: (props: LucideProps) => <MoveLeft {...props} />,
	ArrowLeft: (props: LucideProps) => <ArrowLeft {...props} />,
	ArrowRight: (props: LucideProps) => <ArrowRight {...props} />,
	MoveRight: (props: LucideProps) => <MoveRight {...props} />,
	CornerDownLeft: (props: LucideProps) => <CornerDownLeft {...props} />,
	CornerDownRight: (props: LucideProps) => <CornerDownRight {...props} />,
	PartyPopper: (props: LucideProps) => <PartyPopper {...props} />,
	CopyCheck: (props: LucideProps) => <CopyCheck {...props} />,
	Copy: (props: LucideProps) => <Copy {...props} />,
	Info: (props: LucideProps) => <Info {...props} />,
};
